//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KTiana
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contracts
    {
        public int id_contract { get; set; }
        public int NumberContract { get; set; }
        public int id_client { get; set; }
        public int id_worker { get; set; }
        public int id_service { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Services Services { get; set; }
        public virtual Workers Workers { get; set; }
    }
}
